name: Trigger Jenkins on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins job
        env:
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
        run: |
          curl -X POST http:///192.168.1.215:5000/trigger-job \
            -H "Authorization: Bearer ${{ secrets.JENKINS_PROXY_TOKEN }}" \ 
            -H "Content-Type: application/json" \
            -d '{
              "test_purpose": "certs-platform runs",
              "testbed_name": "stest",
              "rauto_branch": "master",
              "squad_name": "blue",
              "features": "bootstrap_data",
              "test_type": "regression",
              "components": "rafay_platform rafay_services",
              "rafay_interface": "rafay-apiANDrafay-cliANDrafay-terraform",
              "email_address": "musa@rafay.co"
            }'
